### ISSUE TITLE
Make the lexer more friendly towards syntax highlighting

### ISSUE THREAD

**Issue by alessiostalla** [kixi-io/Ki.KD-JVM#1]
Split big tokens (blobs, multi-line strings) into smaller ones using lexer modes.

**Comment by dleuck** [comment]
The syntax highlighting seems to be working well. I'd like to get naked strings to be colored as strings rather than IDs, but per our conversation, it seems like a bit of work to do syntax highlighting with context that isn't coming from the lexer. It may have to wait for later.
